### ISSUE TITLE
Provide the repo as CLI

### ISSUE THREAD

**Issue by long1eu** [aertje/cloud-tasks-emulator#3]
Is there a way to just call this and not have to clone the repo?

**Comment by acoulton** [comment]
It's now a public docker image `docker run ghcr.io/aertje/cloud-tasks-emulator:master` if that helps?

**Comment by ofpiyush** [comment]
Would you accept a PR with https://goreleaser.com/ci/actions/ ?

**Comment by aertje** [comment]
Many thanks @ofpiyush, I've made a small tweak w.r.t. permissions requested in the workflow, and merged from a local branch.
