### ISSUE TITLE
"Established channel does not have a sufficient security level to transfer call credential."

### ISSUE THREAD

**Issue by atrauzzi** [aertje/cloud-tasks-emulator#69]
When following the PHP example, I end up getting the following message:

```
{ "message": "Established channel does not have a sufficient security level to transfer call credential.", "code": 16, "status": "UNAUTHENTICATED", "details": [] }
```

Is there something more that needs to be done when configuring the connection?

**Comment by atrauzzi** [comment]
I also get `Could not construct ApplicationDefaultCredentials`

**Comment by aertje** [comment]
It looks like the client does not respect the overriding configuration when constructed.

I haven't used the PHP client myself, perhaps @mehedimi who added the sample code can help out?

**Comment by mehedimi** [comment]
In my case, I installed the grpc extension version `grpc-1.35.0` by running `pecl install grpc-1.35.0` and the issues were fixed.

**Comment by aertje** [comment]
Did @mehedimi 's suggestion resolve  your issue @atrauzzi ?

**Comment by atrauzzi** [comment]
Apologies, I am no long working on the project where I encountered this issue, so I probably won't be able to recreate or recall the specific criteria.

**Comment by bacheson** [comment]
I'm having this same issue ... anyone find a solution that doesn't involve using a legacy version of grpc?

**Comment by bradjones1** [comment]
This is fixed in the base Google Cloud PHP SDK at https://github.com/googleapis/google-cloud-php/pull/5224.

Opened a PR for update to docs.
